### PR TITLE
Fixed errors in 2-tracer box size and post-processing, improved stability, post-processing optimization etc

### PR DESCRIPTION
**Pull request by misharash**
Probably the most serious change is the prevention of small-scale xi divergence. Instead of going like $1/s$ at $s \rightarrow 0$, it smoothly transitions to constant. This helps to resolve covariance matrix convergence issues in some setups.

Another notable one is optimization of precision matrix calculation in all the post-processings. Apparently the concatenation of lists in covariance-except-this-sample took majority of time there.

Other improvements:
* restored free choice of number of samples for extra convergence check script - helps to find if things go south at some particular point;
* fixed the jackknife extra convergence check script;
* added the option of collapsing samples (averaging all integrals in chunks of $N$ adjacent samples), mostly for faster post-processing, not really used because of the next change;
* made the periodic case respect the given `boxsize` - seems more robust than trying to determine it empirically. Moreover, otherwise a bunch of parameters become redundant unless randoms are generated within RascalC;
* merged `Makefile`s into one - Mac OS can be determined via kernel name, and only 3 lines should be different from Linux.

### CODE REVIEW

**Comment by misharash** [comment]
Last two commits allow compilation both on Apple Silicon and Intel MacOS (at least for the two computers with default Homebrew setups I happened to have).

**Comment by misharash** [comment]
Fixed permutations issues in 2-tracer post-processing. They have been leading to 12,12 covariance being ~1.5x high.

**Comment by misharash** [comment]
- Fixed compilation on MacOS again (hopefully last)
- Fixed some import errors
- Added a short script to print shot-noise rescaling from a RascalC results .npz file

**Comment by misharash** [comment]
Potentially serious: fixed the possibility for different, inconsistent box sizes in 2-tracer mode.

Smaller improvements:

* applied `Makefile` improvements for `triple_counts`;
* fixes and simplifications for jackknife convergence check;
* got rid of a `clang` warning saying `sprintf` is now deprecated by using `snprintf`.

**Comment by oliverphilcox** [comment]
Thanks, sorry I missed this!

**Pull request merged**
